# Generated by Django 5.0.1 on 2024-03-07 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categoryName', models.CharField(max_length=200, null=True)),
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryName', models.CharField(max_length=200, null=True)),
                ('countryId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(default='', max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendorName', models.CharField(default='', max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('date_est', models.DateField()),
                ('location', models.CharField(max_length=1250, null=True)),
                ('address', models.CharField(max_length=3000, null=True)),
                ('contact_tel', models.CharField(max_length=2500, null=True)),
                ('num_of_eployees', models.IntegerField(null=True)),
                ('Int_pro_services', models.CharField(max_length=400, null=True)),
                ('business_areas', models.CharField(max_length=400, null=True)),
                ('client_types', models.CharField(max_length=400, null=True)),
                ('cloud_or_native', models.CharField(max_length=100, null=True)),
                ('added_info', models.CharField(max_length=600, null=True)),
                ('vendorId', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedVendors',
            fields=[
                ('savedVendorsId', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citisoft.client')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citisoft.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorCategories',
            fields=[
                ('vendorCategoriesId', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citisoft.categories')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citisoft.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorRating',
            fields=[
                ('review', models.CharField(max_length=200, null=True)),
                ('rating', models.FloatField(max_length=200)),
                ('vendorRatingId', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citisoft.client')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citisoft.vendor')),
            ],
        ),
    ]
