# Generated by Django 5.0.1 on 2024-03-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citisoft', '0002_saveorder_saveorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
