# Generated by Django 5.0.1 on 2024-03-14 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citisoft', '0004_alter_vendor_date_est'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='countyr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citisoft.country'),
        ),
    ]
